# -*- coding: utf-8 -*-
"""Wine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PDkWsRClz7SY6lO6me3x1PxOeVt8alI
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib

file_path = 'winequality-red (1).csv'

print("Membaca data...")
try:
    df = pd.read_csv(file_path, sep=';')
except FileNotFoundError:
    print(f"Error: File '{file_path}' tidak ditemukan. Pastikan file sudah diupload ke Colab.")
    exit()

print("5 baris pertama data:")
print(df.head())
print("-" * 40)

print("Informasi Data (Cek nilai null dan tipe data):")
df.info()
print("-" * 40)

df['quality_label'] = df['quality'].apply(lambda x: 1 if x >= 7 else 0)

X = df.drop(['quality', 'quality_label'], axis=1) # Hapus kolom 'quality' asli dan yang baru dibuat
y = df['quality_label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(f"Ukuran data pelatihan: {X_train.shape}")
print(f"Ukuran data pengujian: {X_test.shape}")
print("-" * 40)

import numpy as np

# Before scaling, ensure the 'alcohol' column is numeric
# The error message indicates 'alcohol' column has non-numeric values.
# It is currently an 'object' type as seen in df.info().

# Convert 'alcohol' column to numeric, coercing errors to NaN
X_train['alcohol'] = pd.to_numeric(X_train['alcohol'], errors='coerce')
X_test['alcohol'] = pd.to_numeric(X_test['alcohol'], errors='coerce')

# Handle NaN values: Impute with the mean of the training set's 'alcohol' column
# This prevents data leakage from the test set.
alcohol_mean_train = X_train['alcohol'].mean()
X_train['alcohol'].fillna(alcohol_mean_train, inplace=True)
X_test['alcohol'].fillna(alcohol_mean_train, inplace=True)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("Fitur telah distandarisasi.")
print("-" * 40)

print("Melatih Model RandomForestClassifier...")
model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
model.fit(X_train_scaled, y_train)
print("Pelatihan Selesai.")
print("-" * 40)

y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Akurasi Model pada data uji: {accuracy:.4f}")

print("\nLaporan Klasifikasi:")
print(classification_report(y_test, y_pred))
print("-" * 40)

model_filename = 'wine_quality_model.joblib'
scaler_filename = 'wine_quality_scaler.joblib'

joblib.dump(model, model_filename)
joblib.dump(scaler, scaler_filename)

print(f"Model disimpan sebagai: **{model_filename}**")
print(f"Scaler disimpan sebagai: **{scaler_filename}**")
print("\nKedua file ini siap digunakan untuk deployment.")